modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fence_on_slab"
version = "${version}"
displayName = "Fence On Slab!"
authors = "Slainlight"
description = '''
You can finally place fences on slabs!
'''
logoFile = "icon.png"

[[dependencies.fence_on_slab]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fence_on_slab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"