modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fence_on_slab"
version = "0.1.0"
displayName = "Fence On Slab!"
authors = "Slainlight"
description = '''
You can finally place fences on slabs!
'''
logoFile = "icon.png"

[[mixins]]
config = "fence_on_slab-common.mixins.json"

[[dependencies.fence_on_slab]]
modId="minecraft"
type="required"
versionRange="[1.20.5,1.20.6]"

[[dependencies.fence_on_slab]]
modId="neoforge"
type="required"
versionRange="[20.5,)"